Library_Automation_Project/Controllers/EmanetKitaplarController.cs
using Library_Automation.Entities.DAL;
using Library_Automation.Entities.Mapping;
using Library_Automation.Entities.Model;
using Library_Automation.Entities.Model.Contacts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace Library_Automation_Project.Controllers
{
    public class EmanetKitaplarController : Controller
    {
        // GET: EmanetKitaplar
        KutuphaneContext context = new KutuphaneContext();
        EmanetKitaplarDAL EmanetKitaplarDAL = new EmanetKitaplarDAL();
        KitaplarDAL kitaplarDAL = new KitaplarDAL();
        KitapHareketleriDAL kitapHareketleriDAL = new KitapHareketleriDAL();
        public ActionResult Index()
        {
            var model = EmanetKitaplarDAL.GetAll(context, x => x.KitapIadeTarihi == null, "Kitaplar", "Uyeler");
            return View(model);
        }

        public ActionResult Yazdir()
        {
            var model = EmanetKitaplarDAL.GetAll(context, x => x.KitapIadeTarihi == null, "Kitaplar", "Uyeler");
            return new Rotativa.ActionAsPdf("EmanetListesi", model)
            {
                FileName = "EmanetKitaplarListesi.pdf",
                PageSize = Rotativa.Options.Size.A4,
                PageOrientation = Rotativa.Options.Orientation.Portrait,
                CustomSwitches = "--disable-smart-shrinking"

            };
        }

        public ActionResult EmanetListesi()
        {
            var model = EmanetKitaplarDAL.GetAll(context, x => x.KitapIadeTarihi == null, "Kitaplar", "Uyeler");
            return View(model);
        }

        public ActionResult DepositBook()
        {
            ViewBag.UyeListe = new SelectList(context.Uyeler, "Id", "AdiSoyadi");
            ViewBag.KitapListe = new SelectList(context.Kitaplar, "Id", "KitapAdi");

            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult DepositBook(EmanetKitaplar entity)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.UyeListe = new SelectList(context.Uyeler, "Id", "AdiSoyadi");
                ViewBag.KitapListe = new SelectList(context.Kitaplar, "Id", "KitapAdi");
                return RedirectToAction("Index");
            }

            var email = User.Identity.Name;
            var modelKullanici = context.Kullanicilar.FirstOrDefault(k => k.Email == email);

            var kitap = context.Kitaplar.FirstOrDefault(k => k.Id == entity.kitapId);
            var uye = context.Uyeler.FirstOrDefault(u => u.Id == entity.uyeId);

            EmanetKitaplarDAL.InsertorUpdate(context, entity);

            if (modelKullanici != null && kitap != null && uye != null)
            {
                var kitapHareket = new KitapHareketleri
                {
                    KullaniciId = modelKullanici.Id,
                    KitapId = kitap.Id,
                    UyeId = uye.Id,
                    Tarih = DateTime.Now,
                    YapilanIslem = $"{modelKullanici.KullaniciAdi} gave {entity.KitapSayisi} book(s) ({kitap.KitapAdi}) to {uye.AdiSoyadi}"
                };

                kitapHareketleriDAL.InsertorUpdate(context, kitapHareket);
            }

            EmanetKitaplarDAL.Save(context);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            ViewBag.UyeListe = new SelectList(context.Uyeler, "Id", "AdiSoyadi");
            ViewBag.KitapListe = new SelectList(context.Kitaplar, "Id", "KitapAdi");
            var model = EmanetKitaplarDAL.GetByFilter(context, x => x.Id == id, "Uyeler", "Kitaplar");

            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Edit(EmanetKitaplar entity)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.UyeListe = new SelectList(context.Uyeler, "Id", "AdiSoyadi");
                ViewBag.KitapListe = new SelectList(context.Kitaplar, "Id", "KitapAdi");
                return RedirectToAction("Index");
            }

            EmanetKitaplarDAL.InsertorUpdate(context, entity);
            EmanetKitaplarDAL.Save(context);


            return RedirectToAction("Index");
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            EmanetKitaplarDAL.Delete(context, x => x.Id == id);
            EmanetKitaplarDAL.Save(context);
            return RedirectToAction("Index");
        }

        public ActionResult TeslimAl(int? id)
        {
            if (id == null)
                return HttpNotFound();

            var model = EmanetKitaplarDAL.GetByFilter(context, x => x.Id == id, "Kitaplar", "Uyeler");
            if (model == null)
                return HttpNotFound();

            // Set return date
            model.KitapIadeTarihi = DateTime.Now;

            // Update stock
            var kitap = kitaplarDAL.GetByFilter(context, x => x.Id == model.kitapId);
            if (kitap != null)
            {
                kitap.StokAdedi += model.KitapSayisi;
            }

            // Get current user
            var email = User.Identity.Name;
            var kullanici = context.Kullanicilar.FirstOrDefault(k => k.Email == email);

            // Create kitap hareket log
            if (kullanici != null)
            {
                var hareket = new KitapHareketleri
                {
                    KullaniciId = kullanici.Id,
                    KitapId = model.kitapId,
                    UyeId = model.uyeId,
                    Tarih = DateTime.Now,
                    YapilanIslem = $"{model.Uyeler.AdiSoyadi} returned {model.KitapSayisi} books '{kitap.KitapAdi}' to {kullanici.KullaniciAdi}"
                };

                kitapHareketleriDAL.InsertorUpdate(context, hareket);
            }

            EmanetKitaplarDAL.Save(context);
            return RedirectToAction("Index");
        }

    }
}

Library_Automation_Project/Controllers/IstatistiklerController.cs
using ClosedXML.Excel;
using Library_Automation.Entities.DAL;
using Library_Automation.Entities.Model.Contacts;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Library_Automation_Project.Controllers
{
    public class IstatistiklerController : Controller
    {
        KutuphaneContext context = new KutuphaneContext();
        KullaniciHareketleriDAL KullaniciHareketleriDAL = new KullaniciHareketleriDAL();
        KullanicilarDAL KullanicilarDAL = new KullanicilarDAL();
        UyelerDAL UyelerDAL = new UyelerDAL();
        EmanetKitaplarDAL emanetKitaplarDAL = new EmanetKitaplarDAL();
        // GET: Istatistikler
        public ActionResult Index()
        {
            UyelerDAL.UyeKitapIslemleri();
            ViewBag.EnCokUye = UyelerDAL.EnCokUye;
            ViewBag.EnAzUye = UyelerDAL.EnAzUye;
            ViewBag.EnCokSayi = UyelerDAL.EnCokSayi;
            ViewBag.EnAzSayi = UyelerDAL.EnAzSayi;

            ViewBag.UyeKitapModel = UyelerDAL.UyeKitapModel;


            //Kullanici Sayisi
            var KullaniciSayisiModel = KullanicilarDAL.GetAll(context);
            ViewBag.Count = KullaniciSayisiModel.Count;

            var UyeSayisiModel = UyelerDAL.GetAll(context);
            ViewBag.UyeCount = UyeSayisiModel.Count;    

            //En cok giris yapan kullanici adi ve giris sayisi
            var model = KullaniciHareketleriDAL.KullaniciGirisSayilari();
            ViewBag.KullaniciAdi = model.kullaniciAdi;
            ViewBag.GirisSayisi = model.GirisSayisi;

            //KullaniciHareketleri
            KullaniciHareketleriDAL.KullaniciHareketleriGozlemleme();
            ViewBag.AylikVeriler = KullaniciHareketleriDAL.AylikVeriler;
            ViewBag.ToplamKHGSayisi = KullaniciHareketleriDAL.ToplamKHGSayisi;
            ViewBag.AltiAyToplamKHGSayisi = KullaniciHareketleriDAL.AltiAyToplamKHGSayisi;

            // Kitap Türü Sayısı
            ViewBag.KitapTuruSayisi = context.KitapTurleri.Count();

            // Her Kitap Türünden Kaç Tane Var
            var kitapTurGruplari = context.Kitaplar
                .GroupBy(k => k.KitapTurleri.KitapTuru)
                .Select(g => new { KitapTuru = g.Key, Adet = g.Count() })
                .ToList();
            ViewBag.KitapTurGruplari = kitapTurGruplari;

            // Stoku En Fazla Olan Kitap
            var enFazlaStok = context.Kitaplar
                .OrderByDescending(k => k.StokAdedi)
                .FirstOrDefault();
            ViewBag.EnFazlaStokKitap = enFazlaStok;

            // Stoku En Az Olan Kitap (0’dan büyük)
            var enAzStok = context.Kitaplar
                .Where(k => k.StokAdedi > 0)
                .OrderBy(k => k.StokAdedi)
                .FirstOrDefault();
            ViewBag.EnAzStokKitap = enAzStok;


            // En son eklenen kitap
            var latestBook = context.Kitaplar
                .Where(k => !k.SilindiMi)
                .OrderByDescending(k => k.Id)
                .FirstOrDefault();
            ViewBag.LatestBook = latestBook;

            // En çok okunan kitapların Id'leri
            var mostReadBookIds = context.KitapHareketleri
                .GroupBy(h => h.KitapId)
                .Select(g => new
                {
                    KitapId = g.Key,
                    Count = g.Count()
                })
                .OrderByDescending(g => g.Count)
                .Take(3)
                .Select(g => g.KitapId)
                .ToList();

            // En çok okunan kitaplar
            // Silinmemiş kitaplar arasında en çok okunan 3 kitap
            var topBooks = context.KitapHareketleri
                .Where(h => !h.Kitaplar.SilindiMi)
                .GroupBy(h => h.KitapId)
                .Select(g => new
                {
                    Kitap = g.FirstOrDefault().Kitaplar,
                    OkunmaSayisi = g.Count()
                })
                .OrderByDescending(g => g.OkunmaSayisi)
                .Take(3)
                .Select(g => g.Kitap)
                .ToList();

            ViewBag.TopBooks = topBooks;




            return View();
        }

        public ActionResult ExceleAktar()
        {
            using (var workbook = new XLWorkbook())
            {
                var worksheet = workbook.Worksheets.Add("Borrowed Books");
                worksheet.Cell(1, 1).Value = "Id";
                worksheet.Cell(1, 2).Value = "Member Name";
                worksheet.Cell(1, 3).Value = "Book Name";
                worksheet.Cell(1, 3).Value = "Number of Books";
                worksheet.Cell(1, 5).Value = "Date Borrowed";

                var model = emanetKitaplarDAL.GetAll(context, x => x.KitapIadeTarihi == null, "Uyeler", "Kitaplar");

                int row = 2;
                foreach (var item in model)
                {
                    worksheet.Cell(row, 1).Value = item.Id;
                    worksheet.Cell(row, 2).Value = item.Uyeler.AdiSoyadi;
                    worksheet.Cell(row, 3).Value = item.Kitaplar.KitapAdi;
                    worksheet.Cell(row, 4).Value = item.KitapSayisi;
                    worksheet.Cell(row, 5).Value = item.KitapAldigiTarihi;
                    row++;
                }
                using (var stream = new MemoryStream()) //verileri ramde sakliyoruz
                {
                    workbook.SaveAs(stream);
                    stream.Position = 0;
                    return File(stream.ToArray(), "application/vnd.openXmlformats-officedocument.spreadsheetml.Sheet", "EmanetKitaplarSeri.xlsx");
                }


            }
        }
    }
}

Library_Automation_Project/Views/EmanetKitaplar/DepositBook.cshtml
@model Library_Automation.Entities.Model.EmanetKitaplar

@{
    ViewBag.Title = "DepositBook";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="row">
    <div class="col-lg">
        <div class="ibox">
            <div class="ibox-head">
               <b> Borrowing a New Book</b>
            </div>
            <div class="ibox-body">

                @using (Html.BeginForm("DepositBook", "EmanetKitaplar", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(false, "", new { @class = "text-danger" })

                    <div class="form-group">
                        <b>Member :</b>
                        @Html.DropDownListFor(x => x.uyeId, (SelectList)ViewBag.UyeListe, "Select One", new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.uyeId, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <b>Book :</b>
                        @Html.DropDownListFor(x => x.kitapId, (SelectList)ViewBag.KitapListe, "Select One", new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.kitapId, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <b>Number of Book :</b>
                        @Html.TextBoxFor(x => x.KitapSayisi, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.KitapSayisi, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <b>Date Borrowed :</b>
                        @Html.TextBoxFor(x => x.KitapAldigiTarihi, new { @class = "form-control" , type="datetime-local"})
                        @Html.ValidationMessageFor(x => x.KitapAldigiTarihi, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-success">Confirm</button>
                    </div>
                }

            </div>
        </div>
    </div>
</div>

Library_Automation_Project/Views/EmanetKitaplar/Edit.cshtml
@model Library_Automation.Entities.Model.EmanetKitaplar

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="row">
    <div class="col-lg">
        <div class="ibox">
            <div class="ibox-head">
                <b> Editing a Borrowed Book</b>
            </div>
            <div class="ibox-body">

                @using (Html.BeginForm("Edit", "EmanetKitaplar", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(false, "", new { @class = "text-danger" })

                    <div class="form-group">
                        <b>Member :</b>
                        @Html.DropDownListFor(x => x.uyeId, (SelectList)ViewBag.UyeListe, "Select One", new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.uyeId, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <b>Book :</b>
                        @Html.DropDownListFor(x => x.kitapId, (SelectList)ViewBag.KitapListe, "Select One", new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.kitapId, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <b>Number of Book :</b>
                        @Html.TextBoxFor(x => x.KitapSayisi, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.KitapSayisi, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <b>Date Borrowed :</b>
                        @Html.TextBoxFor(x => x.KitapAldigiTarihi, new { @class = "form-control", type = "datetime-local", Value=Model.KitapAldigiTarihi.ToString("yyyy-MM-dd HH:mm") })
                        @Html.ValidationMessageFor(x => x.KitapAldigiTarihi, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-success">Confirm</button>
                    </div>
                }

            </div>
        </div>
    </div>
</div>

Library_Automation_Project/Views/EmanetKitaplar/EmanetListesi.cshtml
@model List<Library_Automation.Entities.Model.EmanetKitaplar>
@{
    ViewBag.Title = "EmanetListesi";
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>Borrowed Book List</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" />
    <style>
        table, th, td {
            border: 1px solid black;
        }

        th, td {
            padding: 8px;
            text-align: left;
        }
    </style>
</head>
<body>
    <div class="container mt-4">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Member</th>
                    <th>Book Name</th>
                    <th>Book Stock</th>
                    <th>Date Borrowed</th>
                    <th>Date Returned</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(x => item.Id)</td>
                        <td>@Html.DisplayFor(x => item.Uyeler.AdiSoyadi)</td>
                        <td>@Html.DisplayFor(x => item.Kitaplar.KitapAdi)</td>
                        <td>@Html.DisplayFor(x => item.KitapSayisi)</td>
                        <td>@Html.DisplayFor(x => item.KitapAldigiTarihi)</td>
                        <td>@Html.DisplayFor(x => item.KitapIadeTarihi)</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>

Library_Automation_Project/Views/EmanetKitaplar/Index.cshtml
@model List<Library_Automation.Entities.Model.EmanetKitaplar>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-lg">
        <div class="ibox">
            <div class="ibox-head">
                Deposit Book List
            </div>
            <div class="ibox-body">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <td>Member</td>
                            <td>Book Name</td>
                            <td>Book Stock</td>
                            <td>Date Borrowed</td>
                            <td>Date Returned</td>
                        </tr>

                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <th>@Html.DisplayFor(x => item.Id)</th>
                                <td>@Html.DisplayFor(x => item.Uyeler.AdiSoyadi)</td>
                                <td>@Html.DisplayFor(x => item.Kitaplar.KitapAdi)</td>
                                <td>@Html.DisplayFor(x => item.KitapSayisi)</td>
                                <td>@Html.DisplayFor(x => item.KitapAldigiTarihi)</td>
                                <td>@Html.DisplayFor(x => item.KitapIadeTarihi)</td>

                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-warning btn-sm" })
                                    <button class="btn btn-danger btn-sm"
                                            onclick="confirmDelete(@item.Id, '@item.Kitaplar.KitapAdi', '@item.Uyeler.AdiSoyadi',)">
                                        Delete
                                    </button>
                                    <button class="btn btn-primary btn-sm"
                                            onclick="confirmReturn(@item.Id, '@item.Kitaplar.KitapAdi', '@item.Uyeler.AdiSoyadi')">
                                        Return
                                    </button>
                                </td>

                            </tr>
                        }

                    </tbody>
                </table>
                @Html.Partial("_DeleteConfirmationModal", "Are you sure you want to delete this book?")

            <div class="form-group">
                @Html.ActionLink("New", "DepositBook", null, new { @class = "btn btn-dark" })--- @Html.ActionLink("Excel Aktar", "ExceleAktar", "Istatistikler", null, new { @class = "btn btn-success" }) ---@Html.ActionLink("Print", "Yazdir", null, new { @class = "btn btn-primary" })


            </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="confirmReturnModal" tabindex="-1" role="dialog" aria-labelledby="confirmReturnModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form id="returnForm" method="post">
                @Html.AntiForgeryToken()
                <div class="modal-header bg-primary text-white">
                    <h5 class="modal-title" id="confirmReturnModalLabel">Confirm Return</h5>
                    <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="returnModalBody">
                    <!-- JavaScript ile doldurulacak -->
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Confirm Return</button>
                </div>
            </form>
        </div>
    </div>
</div>


@section Scripts {
    <script>
        function confirmDelete(bookId, bookName, membername) {
            var form = document.getElementById("deleteForm");
            form.action = "/EmanetKitaplar/Delete/" + bookId;

            var message = `Are you sure you want to delete the borrowed book: <strong>${bookName}</strong> to <strong>${membername}</strong>?`;
            document.getElementById("deleteModalBody").innerHTML = message;

            $('#confirmDeleteModal').modal('show');
        }

        function confirmReturn(bookId, bookName, memberName) {
            var form = document.getElementById("returnForm");
            form.action = "/EmanetKitaplar/TeslimAl/" + bookId;

            var message = `Are you sure you want to return the book: <strong>${bookName}</strong> from <strong>${memberName}</strong>?`;
            document.getElementById("returnModalBody").innerHTML = message;

            $('#confirmReturnModal').modal('show');
        }
    </script>
}