Library_Automation_Project/Controllers/RollerController.cs
using Library_Automation.Entities.DAL;
using Library_Automation.Entities.Model;
using Library_Automation.Entities.Model.Contacts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Library_Automation_Project.Controllers
{
    [Authorize(Roles ="Admin")]
    public class RollerController : Controller
    {
        KutuphaneContext context = new KutuphaneContext();
        RollerDAL rollerDAL = new RollerDAL();
        // GET: Roller
        public ActionResult Index()
        {
            var model = rollerDAL.GetAll(context);
            return View(model);
        }
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Add(Roller entity)
        {
            if(!ModelState.IsValid)
            {
                return View(entity);
            }
            rollerDAL.InsertorUpdate(context, entity);
            rollerDAL.Save(context);
            return RedirectToAction("Index");   
        }

        public ActionResult Edit(int? id)
        {
            if(id == null)
            {
                return HttpNotFound("Id is not entered.");
            }
            var model = rollerDAL.GetByFilter(context, x => x.Id == id);
            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Edit(Roller entity)
        {
            if (!ModelState.IsValid)
            {
                return View(entity);
            }
            rollerDAL.InsertorUpdate(context, entity);
            rollerDAL.Save(context);
            return RedirectToAction("Index");
        }

        public ActionResult DeleteConfirmed(int id)
        {
            rollerDAL.Delete(context, x=>x.Id == id);
            rollerDAL.Save(context);
            return RedirectToAction("Index");
        }
    }
}

Library_Automation_Project/Views/Roller/Add.cshtml
@model Library_Automation.Entities.Model.Roller

@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="row">
    <div class="col-lg">
        <div class="ibox">
            <div class="ibox-head">
                Adding a New Role
            </div>
            <div class="ibox-body">

                @using (Html.BeginForm("Add", "Roller", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(false, "", new { @class = "text-danger" })

                    <div class="form-group">
                        <b>Role :</b>
                        @Html.TextBoxFor(x => x.Rol, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Rol, "", new { @class = "text-danger" })
                    </div>

                  
                    <div class="form-group">
                        <button type="submit" class="btn btn-success">Add</button>
                    </div>
                }

            </div>
        </div>
    </div>
</div>

Library_Automation_Project/Views/Roller/Edit.cshtml
@model Library_Automation.Entities.Model.Roller

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="row">
    <div class="col-lg">
        <div class="ibox">
            <div class="ibox-head">
                Updating a Role
            </div>
            <div class="ibox-body">

                @using (Html.BeginForm("Edit", "Roller", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(false, "", new { @class = "text-danger" })

                    <div class="form-group">
                        <b>Role :</b>
                        @Html.TextBoxFor(x => x.Rol, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Rol, "", new { @class = "text-danger" })
                    </div>


                    <div class="form-group">
                        <button type="submit" class="btn btn-success">Save</button>
                    </div>
                }

            </div>
        </div>
    </div>
</div>

Library_Automation_Project/Views/Roller/Index.cshtml
@model List<Library_Automation.Entities.Model.Roller>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-lg">
        <div class="ibox">
            <div class="ibox-head">
                Role List
            </div>
            <div class="ibox-body">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <td>Roles</td>

                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <th>@Html.DisplayFor(x => item.Id)</th>
                                <td>@Html.DisplayFor(x => item.Rol)</td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-warning btn-sm" })
                                    <button class="btn btn-danger btn-sm"
                                            onclick="confirmDelete(@item.Id, '@item.Rol',)">
                                        Delete
                                    </button>
                                </td>

                            </tr>
                        }

                    </tbody>
                </table>
                @Html.Partial("_DeleteConfirmationModal", "Are you sure you want to delete this book?")

                <div class="form-group">
                    @Html.ActionLink("New", "Add", null, new { @class = "btn btn-success" })

                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        function confirmDelete(roleId, roleName) {
            var form = document.getElementById("deleteForm");
            form.action = "/Roller/DeleteConfirmed/" + roleId;

            var message = `Are you sure you want to delete the role: <strong>${roleName}</strong>?`;
            document.getElementById("deleteModalBody").innerHTML = message;

            $('#confirmDeleteModal').modal('show');
        }
    </script>
}