Library_Automation_Project/Controllers/UyelerController.cs
using Library_Automation.Entities.DAL;
using Library_Automation.Entities.Model;
using Library_Automation.Entities.Model.Contacts;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Library_Automation_Project.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UyelerController : Controller
    {
        KutuphaneContext context = new KutuphaneContext();
        UyelerDAL uyelerDAL = new UyelerDAL();
        // GET: Uyeler
        public ActionResult Index()
        {
            var model = uyelerDAL.GetAll(context);
            return View(model);
        }

        public ActionResult Add()
        {
            return View();
        }
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Add(Uyeler entity, HttpPostedFileBase Resim)
        {
            if (ModelState.IsValid)
            {
                if (Resim != null && Resim.ContentLength > 0)
                {
                    var image = Path.GetFileName(Resim.FileName);
                    string path = Path.Combine(Server.MapPath("~/images"), image);
                    if (System.IO.File.Exists(path) == false)
                    {
                        Resim.SaveAs(path);
                    }
                    entity.Resim = "/images/" + image;
                }
                uyelerDAL.InsertorUpdate(context, entity);
                uyelerDAL.Save(context);
                return RedirectToAction("Index");

            }
            return View(entity);
           
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            var model = uyelerDAL.GetByFilter(context, x => x.Id == id);
            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Edit(Uyeler entity, HttpPostedFileBase Resim)
        {
            if (ModelState.IsValid)
            {
                var model = uyelerDAL.GetByFilter(context, x => x.Id == entity.Id);
                entity.Resim = model.Resim;

                if (Resim != null && Resim.ContentLength > 0)
                {
                    var image = Path.GetFileName(Resim.FileName);
                    string path = Path.Combine(Server.MapPath("~/images"), image);
                    if (System.IO.File.Exists(path) == false)
                    {
                        Resim.SaveAs(path);
                    }
                    entity.Resim = "/images/" + image;
                }
                uyelerDAL.InsertorUpdate(context, entity);
                uyelerDAL.Save(context);
                return RedirectToAction("Index");

                
            }
            return View(entity);

        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            uyelerDAL.Delete(context, x => x.Id == id);
            uyelerDAL.Save(context);
            return RedirectToAction("Index");
        }
    }
}

Library_Automation_Project/Views/Uyeler/Add.cshtml
@model Library_Automation.Entities.Model.Uyeler

@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="row">
    <div class="col-lg">
        <div class="ibox">
            <div class="ibox-head">
                <b>Adding a New Member</b> 
            </div>
            <div class="ibox-body">

                @using (Html.BeginForm("Add", "Uyeler", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(false, "", new { @class = "text-danger" })

                    <div class="form-group">
                        <b>Name and Surname :</b>
                        @Html.TextBoxFor(x => x.AdiSoyadi, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.AdiSoyadi, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <b>Phone Number :</b>
                        @Html.TextBoxFor(x => x.Telefon, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Telefon, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <b>Adress :</b>
                        @Html.TextAreaFor(x => x.Adres, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Adres, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <b>Email</b>
                        @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Email, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <b>Photo</b>
                        @Html.TextBoxFor(x => x.Resim, new { @class = "form-control", type="file" })
                    </div>

                    <div class="form-group">
                        <b>Number of Books Read</b>
                        @Html.TextBoxFor(x => x.OkunanKitapSayisi, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.OkunanKitapSayisi, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <b>Registration Date</b>
                        @Html.TextBoxFor(x => x.KayitTarihi, new { @class = "form-control", type="datetime-local" })
                        @Html.ValidationMessageFor(x => x.KayitTarihi, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success">Add</button>
                    </div>
                }

            </div>
        </div>
    </div>
</div>

Library_Automation_Project/Views/Uyeler/Edit.cshtml
@model Library_Automation.Entities.Model.Uyeler

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="row">
    <div class="col-lg">
        <div class="ibox">
            <div class="ibox-head">
                <b> Updating a Member</b>
            </div>
            <div class="ibox-body">

                @using (Html.BeginForm("Edit", "Uyeler", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(false, "", new { @class = "text-danger" })

                    <div class="form-group">
                        <img src="@Model.Resim" width="100" height="100" />
                    </div>
                    <div class="form-group">
                        <b>Photo :</b>
                        @Html.TextBoxFor(x => x.Resim, new { @class = "form-control", type = "file" })
                    </div>

                    <div class="form-group">
                        <b>Name and Surname :</b>
                        @Html.TextBoxFor(x => x.AdiSoyadi, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.AdiSoyadi, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <b>Phone Number :</b>
                        @Html.TextBoxFor(x => x.Telefon, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Telefon, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <b>Adress :</b>
                        @Html.TextAreaFor(x => x.Adres, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Adres, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <b>Email</b>
                        @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Email, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <b>Number of Books Read</b>
                        @Html.TextBoxFor(x => x.OkunanKitapSayisi, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.OkunanKitapSayisi, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <b>Registration Date</b>
                        @Html.TextBoxFor(x => x.KayitTarihi, new { @class = "form-control", type = "datetime-local", Value = Model.KayitTarihi.ToString("yyyy-MM-dd HH:mm") })
                        @Html.ValidationMessageFor(x => x.KayitTarihi, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success">Add</button>
                    </div>
                }

            </div>
        </div>
    </div>
</div>

Library_Automation_Project/Views/Uyeler/Index.cshtml
@model List<Library_Automation.Entities.Model.Uyeler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-lg">
        <div class="ibox">
            <div class="ibox-head">
                <b>Members List</b>
            </div>
            <div class="ibox-body">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <td>Name and Surname</td>
                            <td>Phone Number</td>
                            <td>Adress</td>
                            <td>Email</td>
                            <td>Photo</td>
                            <td>Registration Date</td>
                            <td>Operations</td>
                        </tr>

                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <th>@Html.DisplayFor(x => item.Id)</th>
                                <td>@Html.DisplayFor(x => item.AdiSoyadi)</td>
                                <td>@Html.DisplayFor(x => item.Telefon)</td>
                                <td>@Html.DisplayFor(x => item.Adres)</td>
                                <td>@Html.DisplayFor(x => item.Email)</td>
                                <td><img src="@item.Resim" width="100" height="100" /></td>
                                <td>@Html.DisplayFor(x => item.KayitTarihi)</td>

                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-warning btn-sm" })
                                    <button class="btn btn-danger btn-sm"
                                            onclick="confirmDelete(@item.Id, '@item.AdiSoyadi')">
                                        Delete
                                    </button>
                                </td>

                            </tr>
                        }

                    </tbody>
                </table>
                @Html.Partial("_DeleteConfirmationModal", "Are you sure you want to delete this book?")

                <div class="form-group">
                    @Html.ActionLink("New", "Add", null, new { @class = "btn btn-success" })

                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        function confirmDelete(memberId, memberName) {
            var form = document.getElementById("deleteForm");
            form.action = "/Uyeler/Delete/" + memberId;

            var message = `Are you sure you want to delete the member: <strong>${memberName}</strong>?`;
            document.getElementById("deleteModalBody").innerHTML = message;

            $('#confirmDeleteModal').modal('show');
        }
    </script>
}